# Generated by Django 5.1 on 2024-08-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_latidude_customuser_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='latidude',
            new_name='latitude',
        ),
    ]
